before_script:
  - export DISTRO_CODENAME=`lsb_release -cs` && echo Using distro $DISTRO_CODENAME
  - apt-get update -yq && apt-get install -y lintian libprotobuf-dev protobuf-compiler

variables:
  GET_SOURCES_ATTEMPTS: "3"
  GIT_DEPTH: "0"
  GIT_SUBMODULE_STRATEGY: "recursive"

#########################
# Templates using anchors
#########################
.amd64_focal_t: &amd64_focal_job
  image: registry.roboception.de/tools/docker_images:focal-buildimage
  tags:
    - amd64
    - docker

.arm64_focal_t: &arm64_focal_job
  image: registry.roboception.de/tools/docker_images:focal-buildimage
  tags:
    - arm64
    - docker

.armhf_focal_t: &armhf_focal_job
  image: registry.roboception.de/tools/docker_images:armhf-focal-buildimage
  tags:
    - armhf
    - docker

.amd64_jammy_t: &amd64_jammy_job
  image: registry.roboception.de/tools/docker_images:jammy-buildimage
  tags:
    - amd64
    - docker

.arm64_jammy_t: &arm64_jammy_job
  image: registry.roboception.de/tools/docker_images:jammy-buildimage
  tags:
    - arm64
    - docker

#############
# Templates
#############
.test:
  stage: test
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - CTEST_OUTPUT_ON_FAILURE=1 make test

# Debian packaging
.package:
  stage: deploy
  script:
    - mkdir build && cd build
    - if [ -n "$ROS_DISTRO" ]; then
        cmake -DCATKIN_BUILD_BINARY_PACKAGE="1" -DCMAKE_INSTALL_PREFIX="/opt/ros/$ROS_DISTRO" -DCMAKE_PREFIX_PATH="/opt/ros/$ROS_DISTRO" -DCMAKE_BUILD_TYPE=Release .. ;
      else
        cmake .. ;
      fi
    - make -j 4
    - make package
    - if [ -z "$APT_REPO" ]; then export APT_REPO=testing; fi
    - upload_deb.sh $DISTRO_CODENAME-$APT_REPO *.deb

.package_testing:
  extends: .package
  only:
    - master
  variables:
    APT_REPO: "testing"

.package_stable:
  extends: .package
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  except:
    - branches
  variables:
    APT_REPO: "stable"

##############
#### Jobs ####
##############
gen_dox:
  <<: *amd64_focal_job
  variables:
    TESTING_DEBS: "true"
  stage: deploy
  script:
    - apt-get install -y doxygen ncftp
    - mkdir build && cd build
    - cmake ..
    - make doc
    - upload_dox.sh doc/html
  only:
    - master
    - tags
  tags:
    - docs

################
# Testing builds
################

# Test (on every commit)
########################
test:focal:amd64:
  <<: *amd64_focal_job
  extends: .test

test:focal:armhf:
  <<: *armhf_focal_job
  extends: .test

test:focal:arm64:
  <<: *arm64_focal_job
  extends: .test

test:jammy:amd64:
  <<: *amd64_jammy_job
  extends: .test

test:jammy:arm64:
  <<: *arm64_jammy_job
  extends: .test

# Deploy testing (only on master)
#################################
package_testing:focal:amd64:
  <<: *amd64_focal_job
  extends: .package_testing

package_testing:focal:armhf:
  <<: *armhf_focal_job
  extends: .package_testing

package_testing:focal:arm64:
  <<: *arm64_focal_job
  extends: .package_testing

package_testing:jammy:amd64:
  <<: *amd64_jammy_job
  extends: .package_testing

package_testing:jammy:arm64:
  <<: *arm64_jammy_job
  extends: .package_testing

################
# Stable builds
################

# Deploy stable (only for releases, version tags)
#################################################
package_stable:focal:amd64:
  <<: *amd64_focal_job
  extends: .package_stable

package_stable:focal:armhf:
  <<: *armhf_focal_job
  extends: .package_stable

package_stable:focal:arm64:
  <<: *arm64_focal_job
  extends: .package_stable

package_stable:jammy:amd64:
  <<: *amd64_jammy_job
  extends: .package_stable

package_stable:jammy:arm64:
  <<: *arm64_jammy_job
  extends: .package_stable

########################
# package as ROS package
########################

ros_testing:noetic:amd64:
  image: ros:noetic-perception
  tags:
    - amd64
    - docker
  extends: .package_testing

ros_stable:noetic:amd64:
  image: ros:noetic-perception
  tags:
    - amd64
    - docker
  extends: .package_stable
